### ISSUE TITLE
[Problem Fix] train CER과 test CER 차이 

### ISSUE THREAD

**Issue by wch18735** [sooftware/Korean-Speech-Recognition#10]
## Bug on [models.speller.forward()](https://github.com/wch18735/Korean-Speech-Recognition/blob/master/models/speller.py)  
    
 KAI.Lib 팀의 원철황입니다.
  
티쳐포싱 미사용시, forward_step() 함수에서 이전 타입스텝의 히든스테이트를 업데이트하고, 다음 셀로 전달해야하는데, 전달되지 않는 문제가 있었습니다.
  
  현재는 문제를 해결했으니 이전에 코드를 다운받아 학습 진행 중이신 분들은 코드를 다시 다운받아 사용해주시기 바랍니다.

감사합니다.

```python
def _forward_step(self, input, hidden, listener_outputs=None, function=F.log_softmax):
        """ forward one time step """
        batch_size = input.size(0)
        output_size = input.size(1)

        embedded = self.embedding(input).to(self.device)
        embedded = self.input_dropout(embedded)

        if self.training:
            self.rnn.flatten_parameters()

        output, hidden = self.rnn(embedded, hidden)

        if self.use_attention:
            output = self.attention(output, listener_outputs)
        else:
            output = output

        output = self.w(output.contiguous().view(-1, self.hidden_size))
        predicted_softmax = function(output, dim=1).view(batch_size, output_size, -1)

        return predicted_softmax, hidden
``` 

![image](https://user-images.githubusercontent.com/49026408/77432948-134d5500-6e22-11ea-813a-90aa0c808a6e.png)

**Comment by Kangjunseo** [comment]
> Traceback (most recent call last):
  File "train.py", line 164, in <module>
    teacher_forcing_ratio = config.teacher_forcing
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\package\trainer.py", line 70, in supervised_train
    y_hat, logit = model(inputs, scripts, teacher_forcing_ratio=teacher_forcing_ratio)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\listenAttendSpell.py", line 49, in forward
    use_beam_search=use_beam_search
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 135, in forward
    function = function
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 82, in _forward_step
    output, hidden = self.rnn(embedded, hidden)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 716, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

sample data를 이용했을 때(제가 가진 데이터또한) 위와 같은 에러가 발생합니다
제 환경은 window10, rtx 2080ti single gpu 입니다

**Comment by wch18735** [comment]
안녕하세요. KAI.Lib팀의 원철황입니다.

먼저 ```.to(self.device)``` 로 되어있는데, 여기 ```device``` 를 print() 해서 확인해주시면 감사하겠습니다.

```RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu```

이 에러는 hidden tenosr 데이터가 gpu 메모리로 올라가지 못 해서 발생하는 문제로 생각됩니다.

```output, hidden = self.rnn(embedded, hidden).to('cuda')``` 로 gpu 메모리에 올려주면 해결할 수 있을 겁니다.

혹시 그래도 문제가 해결되지 않으면 질문 부탁드립니다.

**Comment by wch18735** [comment]
> > Traceback (most recent call last):
> > File "train.py", line 164, in 
> > teacher_forcing_ratio = config.teacher_forcing
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\package\trainer.py", line 70, in supervised_train
> > y_hat, logit = model(inputs, scripts, teacher_forcing_ratio=teacher_forcing_ratio)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
> > return self.module(*inputs[0], **kwargs[0])
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\listenAttendSpell.py", line 49, in forward
> > use_beam_search=use_beam_search
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 135, in forward
> > function = function
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 82, in _forward_step
> > output, hidden = self.rnn(embedded, hidden)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 716, in forward
> > self.dropout, self.training, self.bidirectional, self.batch_first)
> > RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu
> 
> sample data를 이용했을 때(제가 가진 데이터또한) 위와 같은 에러가 발생합니다
> 제 환경은 window10, rtx 2080ti single gpu 입니다

안녕하세요. KAI.Lib팀의 원철황입니다.

먼저 .to(self.device) 로 되어있는데, 여기 device 를 print() 해서 확인해주시면 감사하겠습니다.

RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

이 에러는 hidden tenosr 데이터가 gpu 메모리로 올라가지 못 해서 발생하는 문제로 생각됩니다.

output, hidden = self.rnn(embedded, hidden).to('cuda') 로 gpu 메모리에 올려주면 해결할 수 있을 겁니다.

혹시 그래도 문제가 해결되지 않으면 질문 부탁드립니다.

**Comment by Kangjunseo** [comment]
`cuda = config.use_cuda and torch.cuda.is_available()`
`device = torch.device('cuda' if cuda else 'cpu')`

`print(cuda)`  
`True`

`print(device)`
`cuda`

먼저 device를 확인 했습니다.
그 후에 말씀해주신대로 Speller에서 `output, hidden = self.rnn(embedded, hidden).to('cuda')`로 수정을 해봤지만 같은 문제가 발생했습니다

> Traceback (most recent call last):
  File "train.py", line 164, in <module>
    teacher_forcing_ratio = config.teacher_forcing
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\package\trainer.py", line 70, in supervised_train
    y_hat, logit = model(inputs, scripts, teacher_forcing_ratio=teacher_forcing_ratio)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\listenAttendSpell.py", line 49, in forward
    use_beam_search=use_beam_search
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 135, in forward
    function = function
  File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 82, in _forward_step
    output, hidden = self.rnn(embedded, hidden).to('cuda')     # .to('cuda') 추가
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 716, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

**Comment by wch18735** [comment]
> `cuda = config.use_cuda and torch.cuda.is_available()`
> `device = torch.device('cuda' if cuda else 'cpu')`
> 
> `print(cuda)`
> `True`
> 
> `print(device)`
> `cuda`
> 
> 먼저 device를 확인 했습니다.
> 그 후에 말씀해주신대로 Speller에서 `output, hidden = self.rnn(embedded, hidden).to('cuda')`로 수정을 해봤지만 같은 문제가 발생했습니다
> 
> > Traceback (most recent call last):
> > File "train.py", line 164, in 
> > teacher_forcing_ratio = config.teacher_forcing
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\package\trainer.py", line 70, in supervised_train
> > y_hat, logit = model(inputs, scripts, teacher_forcing_ratio=teacher_forcing_ratio)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
> > return self.module(*inputs[0], **kwargs[0])
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\listenAttendSpell.py", line 49, in forward
> > use_beam_search=use_beam_search
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 135, in forward
> > function = function
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 82, in _forward_step
> > output, hidden = self.rnn(embedded, hidden).to('cuda')     # .to('cuda') 추가
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 716, in forward
> > self.dropout, self.training, self.bidirectional, self.batch_first)
> > RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

해당 부분을 .to(self.device) 로 바꾸어 진행 한 번 부탁드립니다.

**Comment by wch18735** [comment]
> `cuda = config.use_cuda and torch.cuda.is_available()`
> `device = torch.device('cuda' if cuda else 'cpu')`
> 
> `print(cuda)`
> `True`
> 
> `print(device)`
> `cuda`
> 
> 먼저 device를 확인 했습니다.
> 그 후에 말씀해주신대로 Speller에서 `output, hidden = self.rnn(embedded, hidden).to('cuda')`로 수정을 해봤지만 같은 문제가 발생했습니다
> 
> > Traceback (most recent call last):
> > File "train.py", line 164, in 
> > teacher_forcing_ratio = config.teacher_forcing
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\package\trainer.py", line 70, in supervised_train
> > y_hat, logit = model(inputs, scripts, teacher_forcing_ratio=teacher_forcing_ratio)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
> > return self.module(*inputs[0], **kwargs[0])
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\listenAttendSpell.py", line 49, in forward
> > use_beam_search=use_beam_search
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 135, in forward
> > function = function
> > File "C:\Users\nextgen\Desktop\ex\Korean-Speech-Recognition-master\models\speller.py", line 82, in _forward_step
> > output, hidden = self.rnn(embedded, hidden).to('cuda')     # .to('cuda') 추가
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\module.py", line 532, in **call**
> > result = self.forward(*input, **kwargs)
> > File "C:\Users\nextgen\Anaconda3\envs\speech\lib\site-packages\torch\nn\modules\rnn.py", line 716, in forward
> > self.dropout, self.training, self.bidirectional, self.batch_first)
> > RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

_forward_step() 에서 line 82
output, hidden = self.rnn(embeded, hidden)

forward() 에서 line 101
speller_hidden = torch.zeros(self.n_layers, batch_size, self.hidden_size).to(self.device)

로 수정하고 RUN 해보시면 될 것 같습니다.

**Comment by sooftware** [comment]
안녕하세요 강준서님.  
혹시 코드 새로 받으셨나요??  
지금 보내주신 에러를 보니, 코드를 새로 안 받으신거 아닌가해서요.

**Comment by Kangjunseo** [comment]
> 
> 
> 안녕하세요 강준서님.
> 혹시 코드 새로 받으셨나요??
> 지금 보내주신 에러를 보니, 코드를 새로 안 받으신거 아닌가해서요.

네 새로 받았습니다
speller_hidden = torch.zeros(self.n_layers, batch_size, self.hidden_size).to(self.device) 부분을 수정해주니 실행되는 걸 확인했습니다.
감사합니다.
